version:            '3.8'
services:

  bs-database:
    image:          mongo
    restart:        always

  bs-api:
    container_name: bs-api
    build:
      context:      ./bs-api/
      dockerfile:   bs-api.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 1470:1470

  bs-website:
    container_name: bs-website
    build:
      context:      ./bs-website/
      dockerfile:   bs-website.dockerfile
    depends_on:
      - bs-database
    ports:
      - 4200:80

  bs-admin:
    container_name: bs-admin
    build:
      context:      ./bs-admin/
      dockerfile:   bs-website.dockerfile
    depends_on:
      - bs-database
    ports:
      - 5200:80
